# Generated by Django 5.0.1 on 2024-02-05 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Human',
        ),
    ]
