# Generated by Django 5.0.1 on 2024-02-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yo', '0004_alter_human_birthday_alter_human_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='birthday',
        ),
    ]
