# Generated by Django 5.0.1 on 2024-02-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yo', '0005_remove_human_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
    ]
