# Generated by Django 5.0.1 on 2024-02-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yo', '0006_alter_human_mobile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='human',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AddField(
            model_name='human',
            name='image',
            field=models.ImageField(default='def.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='human',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
    ]
